### ISSUE TITLE
HXL/HDX to datapackage conversion

### ISSUE THREAD

**Issue by mcarans** [frictionlessdata/forum#22]
I have started looking at how to convert HXL to a datapackage and made a very simple first example here: https://github.com/mcarans/hxl-frictionless/blob/master/run.py

I would like to extend datapackage to support and specifically identify HXL resources.  Is there any issue with adding new attributes "is_hxl" and "hxl_tag" under the resource?  eg.:
```
    "resources": [
        {
            "url": "xxx",
            "is_hxl": true,
            "schema": {
                "fields": [
                    {
                        "name": "year",
                        "type": "date",
                        "hxl_tag": "#date+year"
                    },
                    {
                        "name": "revisedRequirements",
                        "type": "number",
                        "hxl_tag": "#value+funding+required+usd"
                    },
```
With those attributes then I would consider how to extend datapackage-py to support HXL.

**Comment by rufuspollock** [comment]
FIXED. Looks like this largely got resolved 😄
