### ISSUE TITLE
Provide more information about keywords in a data package

### ISSUE THREAD

**Issue by jen-thomas** [frictionlessdata/forum#26]
For some data packages, I would like to be able to use keywords that come from a controlled vocabulary. 

This would help to improve the quality of the data set by ensuring that keywords are properly described and not misinterpreted (eg. "litter" -> leaf litter, rubbish, litter of animals?). 

Currently the keywords field is an array of strings. I would propose adding something along the lines of: 
- name: string containing the keyword (mandatory)
- source: string of the controlled vocabulary list name (optional)
- uuid: string containing the UUID of the particular keyword (optional)
eg. I'll give an example using the [Global Change Master Directory keywords](https://gcmdservices.gsfc.nasa.gov/static/kms/) and in particular, their [science keywords](https://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/rucontenttype/?format=json)
```
"keywords": [{
"name": "calibration",
"source": "Global Change Master Directory",
"uuid": "ecf29317-bd5e-447b-b911-f8bfb153c83b"
}]
```
I think it would be important to keep the source and uuid fields as optional; there would be many cases where a controlled vocabulary list is not needed.

**Comment by cpina** [comment]
I wonder if it should be like the contributors: https://specs.frictionlessdata.io/data-package/#metadata

It says that it must be an array of objects.

So, I'm wondering if keywords can be an array of strings in some occasions and an array of objects in other occasions or always objects so new properties (e.g. `source` and `uuid` in Jen's proposal) can be added. I think that somewhere in frictionlessdata something could be either but I can't find where right now.

**Comment by rufuspollock** [comment]
@jen-thomas  the `keywords` field should just be a list of strings so i would keep it that way. If you  really need to add other info what about adding a separate field e.g. `keywordsVocab`. Re uuids there's no immediate way  I can think of. Normally i would imagine that sort of information would be stored separately - e.g. you'd store the uuids in the keywords list and have a dictionary of uuid -> tagnames somewhere else.

**Comment by rufuspollock** [comment]
@jen-thomas any thoughts on this? Would this work for your use case?

**Comment by rufuspollock** [comment]
FIXED. I think we have a resolution here. Please feel free to continuing commenting or suggest re-opening.
