### ISSUE TITLE
How to validate a dataset with non matching headers?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/forum#3]
__From @mdonigian__

Hi everyone, I'm trying to get a handle on our csv etl pipelines and goodtables looks like it will do a lot of what I need. However, we have some partners with a bad habit of sending us CSVs with headers that do not conform to the names we asked for in the schema (they are still predictable but not the ones we asked for). I don't see any option for "alias" column names. Does anyone have experience implementing this kind of functionality?

**Comment by roll** [comment]
@mdonigian Hi, our specs/tools match fields with columns by order not by name. You can just ignore `non-matcing-header` error in `goodtables`: `goodtables.validate(..., skip_checks=['non-matching-header'])`

**Comment by rufuspollock** [comment]
FIXED.
