### ISSUE TITLE
Start an "Awesome Frictionless" section / repo and put it on the main site too

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/forum#32]
There's a lot of cool stuff getting done and we want a place to collect and display this  that is easy to contribute to and easy to find. "Awesome" is a growing convention for this kind of associated tools, tips etc.

### csv-schema by @timwis

http://csv-schema.surge.sh/

https://github.com/timwis/csv-schema

**Comment by lwinfree** [comment]
I think having a dedicated section for this kind of stuff would be great! Right now, some of it lives here https://frictionlessdata.io/tooling/labs/ & we also have a 'use cases' navbar header. We used to call this stuff "universe". I would not call it "Awesome Frictionless" as I don't think it is clear what that means. Maybe "Partner Projects"? I think we should have a section under 'use cases' for all of this - what do others think?

**Comment by rufuspollock** [comment]
@lwinfree i agree about naming on website - it is just awesome is convention for the repo. I think we could have the repo and then put relevant content on site under any good name we think of.

**Comment by lauragift21** [comment]
FIXED. We've setup the awesome repo https://github.com/frictionlessdata/awesome-frictionless
