### ISSUE TITLE
Website alias for frictionlessdata.io

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/forum#4]
I see our group often calling the website frictionlessdata.io by a shortened alias FD.io.

However, fd.io is an existing website that has nothing to do with Frictionless Data.

How about we use the alias f11d.io or f11data.io, instead? Those at least aren't real websites. Or maybe we should register these domains and redirect them to frictionlessdata.io.

As a bonus, f11d.io could even double down in utility as a URL shortener for Data Packages. We could use a URL shortener [tool](https://github.com/thedevs-network/kutt) but restrict it to accept only data packages. WDYT?

**Comment by rufuspollock** [comment]
FIXED. Good point and 👍 for f11d.io for now 😄

**Comment by johanricher** [comment]
I like the URL shortener idea. f11d.io should definitely be reserved ASAP.
