### ISSUE TITLE
Unable to read google spreadsheets using tabulator package

### ISSUE THREAD

**Issue by Swarnitha-eluru** [frictionlessdata/forum#52]
I wrote the sample snippet given by you it worked for your google spreadsheet.
Then I gave my own google spreadsheet link .
![image](https://user-images.githubusercontent.com/46745717/84636542-51827e00-af12-11ea-8c84-85918a6e0a78.png)

I am  getting the error response as follows:
**tabulator.exceptions.FormatError: Format has been detected as HTML (not supported)**

**Comment by roll** [comment]
@Swarnitha-eluru 
Hi, I think the problem in the permissions. You need to make it publically accessible (e.g. everyone can access by a sharable link)

**Comment by Swarnitha-eluru** [comment]
okay thank you.I gave public access for my sheet and checked .I am able to read data for the google spreadsheets
